###
GET http://localhost:8080/players

###
POST http://localhost:8080/players
Content-Type: application/json

{
  "name": "De'Aaron Fox",
  "position": "Guard",
  "currentTeam": "Sacramento Kings",
  "nationality": "USA",
  "jerseyNumber": 5,
  "height": { "feet": 6, "inches": 3 },
  "weight": 185,
  "birthdate": "1990-01-01",
  "email": "deaaron.fox@example.com"
}


###
PUT http://localhost:8080/players/655697c1df751dfa7fb56013
Content-Type: application/json

{
  "name": "De'Aaron Sooox",
  "position": "Guard",
  "currentTeam": "Sacramento Kings",
  "nationality": "USA",
  "jerseyNumber": 99,
  "height": { "feet": 7, "inches": 3 },
  "weight": 185,
  "birthdate": "1991/01/01",
  "email": "deaaron.fox@example.com"
}


###
DELETE http://localhost:8080/players/655697c1df751dfa7fb56013



### GET ALL players
GET https://basketball4676.onrender.com/players

### Create New player
POST https://basketball4676.onrender.com/players HTTP/1.1
Content-Type: application/json

{
  "name": "De'Aaron Sooox",
  "position": "Guard",
  "currentTeam": "Sacramento Kings",
  "nationality": "USA",
  "jerseyNumber": 99,
  "height": { "feet": 7, "inches": 3 },
  "weight": 185,
  "birthdate": "1991/01/01",
  "email": "deaaron.fox@example.com"
}

### Update a existing player
PUT https://basketball4676.onrender.com/players/65563c40fe8ed34bcec7a52a
Content-Type: application/json

{
  "name": "De'Aaron Sooox",
  "position": "Guard",
  "currentTeam": "Sacramento Kings",
  "nationality": "USA",
  "jerseyNumber": 99,
  "height": { "feet": 7, "inches": 3 },
  "weight": 185,
  "birthdate": "1991/01/01",
  "email": "deaaron.fox@example.com"
}
### Delete a existing player
DELETE https://basketball4676.onrender.com/players/655583dbef086a21d032bc6b
