###
GET http://localhost:8080/teams

###
POST http://localhost:8080/teams
Content-Type: application/json

{
  "nickName": "Kings",
  "cityName": "Sacramento",
  "coach": "Mike Brown",
  "homeArena": "Golden 1 Center",
  "founded": 1923,
  "championships": 1, 
  "conference": "Western",
  "division": "Pacific Division"
}


###
PUT http://localhost:8080/teams/6556583b25742618036939b9
Content-Type: application/json

{
  "nickName": "Nuggets",
  "cityName": "Denver",
  "coach": "Michael Malone",
  "homeArena": "Ball Arena",
  "founded": 1967,
  "championships": 1, 
  "conference": "Western",
  "division": "Northwest"
}


### DELETE a existing team with the team _id
DELETE http://localhost:8080/teams/6556575e25742618036939b5



### GET ALL teams
GET https://basketball4676.onrender.com/teams

### Create New team
POST https://basketball4676.onrender.com/teams HTTP/1.1
Content-Type: application/json

{
  "nickName": "Suns",
  "cityName": "Phoenix",
  "coach": "Monty Williams",
  "homeArena": "Footprint Center",  
  "founded": 1968,
  "championships": 0,
  "conference": "Western",
  "division": "Pacific"
}


### Update a existing team
PUT https://basketball4676.onrender.com/teams/655583dbef086a21d032bc6b
Content-Type: application/json

{
"nickName": "Mavericks",
"cityName": "Dallas",
"coach": "Jason Kidd",
"homeArena": "American Airlines Center",
"founded": 1980,
"championships": 4,
"conference": "Western",
"division":"Southwest"
}
### DELETE a existing team with the team _id
DELETE https://basketball4676.onrender.com/teams/655583dbef086a21d032bc6b
